title: "Runzbuzz"
description: "A tech blog about Artificial Intelligence and Business stuff"
remote_theme: runzbuzz/blog-theme@master
#permalink: pretty
permalink: /posts/:title

url: "https://blog.runzbuzz.com"

author:
  name: "Ahmad Alobaid"
  email: ""
  url: "https://consulting.runzbuzz.com"
keywords: [AI, Artificial Intelligence, Data Science, Machine Learning, Blog]

company:
  name: "Runzbuzz"
  url: "https://consulting.runzbuzz.com"


# Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]


# Pagination
paginate: 5
paginate_path: "/page-:num/"


#SEO
twitter:
  username: runzbuzz
  card: summary
facebook:
  app_id: 
logo: /assets/img/runzbuzz.png
social:
  name: Runzbuzz
  links:
    - https://github.com/runzbuzz
    - https://x.com/runzbuzz
    - https://www.linkedin.com/in/ahmadalobaid/
lang: en
