
#Pages
pages:
  - {name: 'about', link: 'about.html'}
  - {name: 'categories', link: 'categories'}
#  - {name: 'Patreon', link: '#'}
#  - {name: 'Shop', link: '#'}
#  - {name: 'GitHub', link: 'https://github.com/PandaSekh'}
#  - {name: 'Get This Theme', link: 'https://github.com/PandaSekh/Jekyll-Podcaster'}

social:
  - {icon: 'instagram', type: "brand", link: 'https://www.instagram.com/runzbuzz/'}
  - {icon: 'twitter', type: "brand", link: 'https://www.x.com/runzbuzz'}
  - {icon: 'linkedin', type: "brand", link: 'https://www.linkedin.com/company/4816289/'}
#  - {icon: 'facebook', type: "brand", link: '#'}
#  - {icon: 'youtube', type: "brand", link: '#'}  
#  - {icon: 'envelope', type: "solid", link: 'mailto:alessiofranceschi2@gmail.com'}
#  - {icon: 'rss', type: "solid", link: "#"}
